### ISSUE TITLE
Actividad 3 Cuadro comparativo 

### ISSUE THREAD

**Issue by Vanessacruzortiz** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-Vanessacruzortiz#1]
[ACTIVIDAD 3 CUADRO COMPARATIVO 1BS VANESSA CRUZ ORTIZ.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-Vanessacruzortiz/files/9481688/ACTIVIDAD.3.CUADRO.COMPARATIVO.1BS.VANESSA.CRUZ.ORTIZ.pdf)

**Comment by Daisy-GonzalezLita12** [comment]
18.3

**Comment by josealfredo79** [comment]
Es un cuadro comparativo...minimo debe tener tres columnas...se debe volver a realizar el trabajo

**Comment by Vanessacruzortiz** [comment]
Actividad 3 cuadro comparativo 1BS
[ACTIVIDAD 3 CUADRO COMPARATIVO VANESSA CRUZ ORTIZ.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-Vanessacruzortiz/files/9523485/ACTIVIDAD.3.CUADRO.COMPARATIVO.VANESSA.CRUZ.ORTIZ.pdf)

**Comment by Daisy-GonzalezLita12** [comment]
Le faltaron elementos a comparar, le falto igual justificar su texto, 14.5 de 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
